### ISSUE TITLE
Could you suggest a Zookeeper image?

### ISSUE THREAD

**Issue by uksus70** [axuan25/kaa-docker#1]
There are so many Zookeeper images on Docker hub, and there is no official image. Could you suggest one that you use successfully?

Thanks.

**Comment by axuan25** [comment]
Hi Anthony,

I use jplock's image.
-> https://hub.docker.com/r/jplock/zookeeper/~/dockerfile/

I personally like to copy the dockerfile to make minor edits, such as
adding custom configs and exposing volumes for data containers. However,
the 3.4.8 tag has worked fine for months with me.

Btw: I just pushed a minor update the kaa-docker repo, I forgot to add curl
which was causing rpc bugs. I'm currently using the image without issues so
far.

Best,
Christopher

Christopher Burroughs 歐陽軒
B.A. Asian Studies, Option I: China & Taiwan
University of California, Berkeley | 2014
+1-714-752-3340 | axuan@chrisplusplus.net

On Mon, Apr 11, 2016 at 3:19 AM, Anthony Serdyukov <notifications@github.com

**Comment by uksus70** [comment]
Thank you! I'm going to give it a try.

**Comment by uksus70** [comment]
Worked, thanks!
However using docker-compose version 2 file `ZOOKEEPER_PORT_2181_TCP_ADDR` [is not populated automatically](https://docs.docker.com/compose/link-env-deprecated/), so I had to specify `ZOOKEEPER_IP` environment variable manually.
